name: Download and Publish Files

on:
  schedule:
    - cron: '0,30 * * * *'  # 每半小时执行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  download_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set timezone to Beijing
      run: |
        sudo timedatectl set-timezone Asia/Shanghai

    - name: Log current datetime in Beijing timezone
      run: |
        echo "Current Beijing time: $(date '+%Y-%m-%d-%H:%M:%S')"

    - name: Download files
      env:
        DOWNLOAD_LINKS: ${{ secrets.DOWNLOAD_LINKS }}
      run: |
        IFS=',' read -ra LINKS <<< "$DOWNLOAD_LINKS"
        MAX_RETRIES=3

        for link in "${LINKS[@]}"; do
          filename=$(basename "$link")
          echo "Downloading $filename"
          
          retries=0
          success=false
          
          while [ $retries -lt $MAX_RETRIES ]; do
            curl -o "$filename" "$link"
            
            if [ $? -eq 0 ]; then
              echo "Successfully downloaded $filename"
              success=true
              break
            else
              retries=$((retries + 1))
              echo "Failed to download $filename. Retry $retries/$MAX_RETRIES..."
              sleep 2
            fi
          done
          
          if [ "$success" = false ]; then
            echo "Failed to download $filename after $MAX_RETRIES attempts."
            exit 1
          fi
        done

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Update files - $(date '+%Y-%m-%d-%H:%M:%S')"
        git push
