name: Download and Publish Files

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  download_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set timezone to Beijing
      run: |
        sudo timedatectl set-timezone Asia/Shanghai

    - name: Log current datetime in Beijing timezone
      id: beijing_time
      run: |
        echo "Current Beijing time: $(date '+%Y-%m-%d-%H:%M:%S')"
        echo "time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

    - name: Download files
      env:
        DOWNLOAD_LINKS: ${{ secrets.DOWNLOAD_LINKS }}
      run: |
        IFS=',' read -ra LINKS <<< "$DOWNLOAD_LINKS"
        MAX_RETRIES=3
        UPDATED_FILES=""
        for link in "${LINKS[@]}"; do
          filename=$(basename "$link" | cut -d '?' -f 1)
          echo "Downloading $filename"
          
          retries=0
          success=false
          
          while [ $retries -lt $MAX_RETRIES ]; do
            curl -o "$filename" "$link"
            
            if [ $? -eq 0 ]; then
              echo "Successfully downloaded $filename"
              UPDATED_FILES="$UPDATED_FILES $filename"
              success=true
              break
            else
              retries=$((retries + 1))
              echo "Failed to download $filename. Retry $retries/$MAX_RETRIES..."
              sleep 2
            fi
          done
          
          if [ "$success" = false ]; then
            echo "Failed to download $filename after $MAX_RETRIES attempts."
            exit 1
          fi
        done
        echo "updated_files=$(echo $UPDATED_FILES | xargs)" >> $GITHUB_ENV

    - name: Capture Git Changes for Each File
      id: file_stats
      run: |
        LOG_ENTRIES=""
        TOTAL_ADDED=0
        TOTAL_DELETED=0
        FILE_COUNT=0

        for file in ${{ env.updated_files }}; do
          ADDED_LINES=$(git diff --cached --numstat "$file" | awk '{added += $1} END {print added}')
          DELETED_LINES=$(git diff --cached --numstat "$file" | awk '{deleted += $2} END {print deleted}')

          [ -z "$ADDED_LINES" ] && ADDED_LINES=0
          [ -z "$DELETED_LINES" ] && DELETED_LINES=0
          
          LOG_ENTRIES="$LOG_ENTRIES\n$file | Lines Added: $ADDED_LINES | Lines Deleted: $DELETED_LINES"
          TOTAL_ADDED=$((TOTAL_ADDED + ADDED_LINES))
          TOTAL_DELETED=$((TOTAL_DELETED + DELETED_LINES))
          FILE_COUNT=$((FILE_COUNT + 1))
        done

        echo "log_entries=$LOG_ENTRIES" >> $GITHUB_ENV
        echo "total_added=$TOTAL_ADDED" >> $GITHUB_ENV
        echo "total_deleted=$TOTAL_DELETED" >> $GITHUB_ENV
        echo "file_count=$FILE_COUNT" >> $GITHUB_ENV

    - name: Update Log File
      run: |
        LOG_FILE="update_log.txt"
        TOTAL_LOG_ENTRY="Total Today: ${{ env.date }} | Files Updated: ${{ env.file_count }} | Lines Added: ${{ env.total_added }} | Lines Deleted: ${{ env.total_deleted }}\n"
        NEW_LOG_ENTRY="Update Time: ${{ env.time }} | Files Updated: ${{ env.file_count }} | Lines Added: ${{ env.total_added }} | Lines Deleted: ${{ env.total_deleted }}\n${{ env.log_entries }}\n---\n"

        # Create the log file if it does not exist
        touch "$LOG_FILE"
        
        if grep -q "^Total Today: ${{ env.date }} " "$LOG_FILE"; then
          # Update today's log entry if it exists
          TODAY_ENTRY=$(grep -E "^Total Today: ${{ env.date }} " "$LOG_FILE")
          
          TODAY_TOTAL_ADDED=$(echo "$TODAY_ENTRY" | awk -F'|' '{print $3}' | awk '{print $3}')
          TODAY_TOTAL_DELETED=$(echo "$TODAY_ENTRY" | awk -F'|' '{print $4}' | awk '{print $3}')
          TODAY_FILE_COUNT=$(echo "$TODAY_ENTRY" | awk -F'|' '{print $2}' | awk '{print $3}')
          
          TODAY_TOTAL_ADDED=$((TODAY_TOTAL_ADDED + ${{ env.total_added }}))
          TODAY_TOTAL_DELETED=$((TODAY_TOTAL_DELETED + ${{ env.total_deleted }}))
          TODAY_FILE_COUNT=$((TODAY_FILE_COUNT + ${{ env.file_count }}))
          
          UPDATED_TODAY_LOG_ENTRY="Total Today: ${{ env.date }} | Files Updated: $TODAY_FILE_COUNT | Lines Added: $TODAY_TOTAL_ADDED | Lines Deleted: $TODAY_TOTAL_DELETED"
          sed -i "s/^Total Today: ${{ env.date }} .*$/$UPDATED_TODAY_LOG_ENTRY/" "$LOG_FILE"
        else
          # Prepend today's log entry if it does not exist
          sed -i "1i$TOTAL_LOG_ENTRY" "$LOG_FILE"
        fi

        # Prepend the new log entry to the file
        sed -i "2i$NEW_LOG_ENTRY" "$LOG_FILE"

        cat "$LOG_FILE"

    - name: Send Telegram Notification
      run: |
        TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID=${{ secrets.TELEGRAM_CHAT_ID }}
        MESSAGE="更新完成：
总计今天：${{ env.date }} | 更新文件数：${{ env.file_count }} | 新增行数：${{ env.total_added }} | 删除行数：${{ env.total_deleted }}
本次更新时间：$${{ env.time }} | 更新文件数：${{ env.file_count }} | 新增行数：${{ env.total_added }} | 删除行数：${{ env.total_deleted }}
${{ env.log_entries }}"
        
        # 使用 urlencode 对特殊字符进行编码
        ENCODED_MESSAGE=$(echo "$MESSAGE" | jq -sRr @uri)
        curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
             -d "chat_id=$CHAT_ID" \
             -d "text=$ENCODED_MESSAGE" \
             -d "parse_mode=HTML"

    - name: Commit changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git add .
        git commit -m "Update files - $(date '+%Y-%m-%d-%H:%M:%S')"
        git push
