name: Download and Publish Files

on:
  workflow_dispatch:  # 允许手动触发

jobs:
  download_and_publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set timezone to Beijing
      run: |
        sudo timedatectl set-timezone Asia/Shanghai

    - name: Log current datetime in Beijing timezone
      id: beijing_time
      run: |
        echo "Current Beijing time: $(date '+%Y-%m-%d-%H:%M:%S')"
        echo "time=$(date '+%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "date=$(date '+%Y-%m-%d')" >> $GITHUB_ENV

    - name: Download files
      env:
        DOWNLOAD_LINKS: ${{ secrets.DOWNLOAD_LINKS }}
      run: |
        IFS=',' read -ra LINKS <<< "$DOWNLOAD_LINKS"
        MAX_RETRIES=3
        UPDATED_FILES=""
        for link in "${LINKS[@]}"; do
          filename=$(basename "$link" | cut -d '?' -f 1)
          echo "Downloading $filename"
          
          retries=0
          success=false
          
          while [ $retries -lt $MAX_RETRIES ]; do
            curl -o "$filename" "$link"
            
            if [ $? -eq 0 ]; then
              echo "Successfully downloaded $filename"
              UPDATED_FILES="$UPDATED_FILES $filename"
              success=true
              break
            else
              retries=$((retries + 1))
              echo "Failed to download $filename. Retry $retries/$MAX_RETRIES..."
              sleep 2
            fi
          done
          
          if [ "$success" = false ]; then
            echo "Failed to download $filename after $MAX_RETRIES attempts."
            exit 1
          fi
        done
        echo "updated_files=$(echo $UPDATED_FILES | xargs)" >> $GITHUB_ENV

    - name: Capture Git Changes for Each File
      id: file_stats
      run: |
        LOG_ENTRIES=""
        TOTAL_ADDED=0
        TOTAL_DELETED=0
        FILE_COUNT=0

        for file in ${{ env.updated_files }}; do
          # Check if file is modified
          if git diff --cached --quiet "$file"; then
            continue
          fi

          ADDED_LINES=$(git diff --cached --numstat "$file" | awk '{added += $1} END {print added}')
          DELETED_LINES=$(git diff --cached --numstat "$file" | awk '{deleted += $2} END {print deleted}')

          [ -z "$ADDED_LINES" ] && ADDED_LINES=0
          [ -z "$DELETED_LINES" ] && DELETED_LINES=0
          
          # Only add file to log if it has changes
          if [ "$ADDED_LINES" -ne 0 ] || [ "$DELETED_LINES" -ne 0 ]; then
            LOG_ENTRIES="$LOG_ENTRIES$file | Lines Added: $ADDED_LINES | Lines Deleted: $DELETED_LINES\n"
            TOTAL_ADDED=$((TOTAL_ADDED + ADDED_LINES))
            TOTAL_DELETED=$((TOTAL_DELETED + DELETED_LINES))
            FILE_COUNT=$((FILE_COUNT + 1))
          fi
        done

        # Store the results in environment variables only if there are changes
        if [ "$FILE_COUNT" -ne 0 ]; then
          echo "log_entries=$LOG_ENTRIES" >> $GITHUB_ENV
          echo "total_added=$TOTAL_ADDED" >> $GITHUB_ENV
          echo "total_deleted=$TOTAL_DELETED" >> $GITHUB_ENV
          echo "file_count=$FILE_COUNT" >> $GITHUB_ENV
        else
          echo "No files changed."
          echo "log_entries=" >> $GITHUB_ENV
          echo "total_added=0" >> $GITHUB_ENV
          echo "total_deleted=0" >> $GITHUB_ENV
          echo "file_count=0" >> $GITHUB_ENV
        fi

    - name: Update Log File
      run: |
        LOG_FILE="update_log.txt"
        TOTAL_LOG_ENTRY="今天: ${{ env.date }} | 更新文件: ${{ env.file_count }} | 新增行: ${{ env.total_added }} | 删除行: ${{ env.total_deleted }}"
        NEW_LOG_ENTRY="本次: ${{ env.time 
